### ISSUE TITLE
_**, for example, _download. is _ be vanilla js syntax? what call?

### ISSUE THREAD

**Issue by anlexN** [tcorral/Design-Patterns-in-Javascript#11]

**Comment by tcorral** [comment]
Hi, @anlexN.  

Could you provide more information about what's the issue, please?

**Comment by anlexN** [comment]
I mean _ prefix is a syntax?

**Comment by tcorral** [comment]
It's just a way to inform other developers that these methods, functions or attributes are supposed to be kept private. Even JsDoc uses this naming convention to add the comments. 

![image](https://user-images.githubusercontent.com/802081/37485557-1438e32c-288c-11e8-8b5f-65cda339ae12.png)

You can find also another example in this url: 
http://2ality.com/2016/01/private-data-classes.html#marking-private-properties-via-a-naming-convention
